# NumPy Exercises 



#### Import NumPy as np

In [7]:
import numpy as np #np used to call the numpy library and related functions and data types.

#### Create an array of 10 zeros 

In [3]:
np.zeros(10) #make array contian 10 column and one row of zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10) #make array contian 10 column and one row of one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [8]:
np.ones(10)*5 #multple 5 *array(0,10) ones

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [14]:
#another solution
arr= np.arange(0,11)             #make array from 0 to 10
slice_of_arr[:]=5                #put five in every element of array

slice_of_arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [12]:
arr= np.arange(10,51)  #make array from 10 to 50
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [13]:
arr= np.arange(10,51,2) #make array from 10 to 50 with 2 step
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
my_matrix =[[0,1,2],[3,4,5],[6,7,8]]  #iput the matrix
my_matrix                              
x=np.array(my_matrix)                 #put array matrix in variable
x                                     #call the matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [15]:
np.eye(3)          #(diagonal matrix) matrix * inverse of the same matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [16]:
np.random.rand(1) #make array contain one random element

array([0.1255273])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
np.random.randn(25) #make array contain 25 random element

array([-0.70991146, -0.68375653, -0.08428514, -1.57842666, -0.29844598,
       -0.34462468,  1.75690995,  0.42928503,  0.99395663,  1.45692597,
       -0.42176092,  0.72735177,  0.26547617,  2.00762533,  0.37544486,
        0.20528514,  1.03188727,  0.39533848,  0.12288033,  1.15142984,
       -0.25823314, -0.07904717, -0.56433547, -1.74762582,  0.99057283])

#### Create the following matrix:

In [49]:
arr= np.arange(0.01,1.01,0.01) #make array contian from 0.01 to 1.01 with 0.01 step
arr.reshape(10,10) # give a new shape to an array without changing its data

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [50]:
np.linspace(0,1,20) #make array  Consist of 0 to 1 in 20 element with the same step

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [17]:
mat = np.arange(1,26).reshape(5,5) 
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [19]:
mat[2:,1:]  #2: all after row 2 and all after column one

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [21]:
mat[3,4] # element of row 3 and colomn 4 

20

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [23]:
mat[:3,1:2] #:3 all before row 3 and all after column one and before 2 mean colomn one

array([[ 2],
       [ 7],
       [12]])

In [25]:
#another solution
x=mat[:3,1]     #:3 all before row 3 and column one 
x.reshape(3,1)  # give a new shape to an array without changing its data

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [70]:
mat[4,0:] #:row 4 and all after column 0

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [72]:
mat[3:,0:] #3: all after row 3 and all after column zero 

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [84]:
mat.sum() #adding all matrix

325

#### Get the standard deviation of the values in mat

In [26]:
np.std(mat) ##### Get the standard deviation of the values in mat

7.211102550927978

#### Get the sum of all the columns in mat

In [101]:
np.sum(mat,0)          # axis=0 to Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

In [103]:
np.sum(mat, 1)       # axis=1 to Get the sum of all the rows in mat

array([ 15,  40,  65,  90, 115])

# Great Job!