## Write a Numpy program to compute the multiplication of two given matrixes

In [18]:
import numpy as np                                  #np used to call the numpy library and related functions and data types.

In [19]:
matrix1 =[[0,1,2],[3,4,5],[6,7,8]]  #iput the matrix
matrix2 =[[0,1,2],[5,5,5],[0,0,0]]  #iput the matrix                             
x=np.array(matrix1)                 #put array matrix in variable
y=np.array(matrix2)                 #put array matrix in variable
x * y

array([[ 0,  1,  4],
       [15, 20, 25],
       [ 0,  0,  0]])

## Write a NumPy program to compute the determinant of a given square array

In [33]:
matrix = np.array([[2, 1], [2, 2]]) ##make square array: 2*2...determinant: 2*2-1*2=2
matrix

array([[2, 1],
       [2, 2]])

In [34]:
np.linalg.det(matrix)  # np. linalg. det() function calculates the determinant of the input matrix. 

2.0

## Write a NumPy program to compute the cross product of two given vectors

In [49]:
a =[[0, 1], [4, 2]]  #iput the matrix
b =[[2, 1], [2, 2]]  #iput the matrix                             
x=np.cross(a , b)  # The cross product of two vectors, a and b, is denoted by a × b. Its resultant vector is perpendicular to a and b.  
x             

array([-2,  4])

In [50]:
y=np.cross(b, a)   # The cross product of two vectors, b and a, is denoted by b × a. Its resultant vector is perpendicular to b and a.       
y

array([ 2, -4])

## Write a NumPy program to compute the condition number of a given matrix

In [61]:
from numpy import linalg as LA   
a=[[0, 1], [4, 2]]  #iput the matrix
np.array(a)
a


[[0, 1], [4, 2]]

In [62]:
LA.cond(a) #compute the condition number of a given matrix

5.0520609798684495

## Write a NumPy program to compute the inverse of a given matrix

In [64]:
matrix = np.array([[2, 1], [2, 2]]) #make square array: 2*2
matrix

array([[2, 1],
       [2, 2]])

In [65]:
np.linalg.inv(matrix)  #linalg. inv() function. This function is used to calculate the multiplicative inverse of the input matrix.

array([[ 1. , -0.5],
       [-1. ,  1. ]])